### PR TITLE
feat(qwen3.8): add paired ONNX execution

### PR DESCRIPTION
**Pull request by JCalafato**
## Background

The Qwen3.8 family needs explicit mixed-NVFP4 target plus DSpark block7 execution through the pinned official Edge-LLM ONNX toolchain. The ordinary experimental builder path is not qualified and is intentionally absent from this change. Standalone Model Connect builds retain their original native path.

## Exit Criteria

- Forward the explicit Qwen3.8 target/draft pair through Model Connect to the original ONNX exporter, native builder and C++ runtime.
- Preserve supported generation controls, reject unmapped semantics and pass unchanged independent quality gates on the qualified SM120 profile.
- Keep all model admission, orchestration, artifact ownership and validation family-local. Do not add Qwen3 or older support.

## Implementation

- Add a family-owned named-draft entrypoint and exact native SM120 route for mixed-NVFP4 DSpark block7.
- Package both speculative engines and their embedding/head/tokenizer assets without duplicating source weights. The family runtime uses draft topK1/step1/verify8 with scheduling off.
- Derive admitted single-user prompt prefix/suffix mappings from the checkpoint tokenizer and preserve supported sampling controls. Reject unsupported generation requests and capacity overflow.
- Fix the existing E2E helper to pass companion inputs, preserve failed CLI output and decode declared ModelOpt mixed weights for its independent CPU FP32 oracle. No thresholds are weakened.
- Update the family recipe and documentation website. Extra rollout-only test files remain local, not in this PR.

### Change categories

- [x] Model or runtime behavior
- [x] Public API
- [ ] ABI
- [x] Bundle or artifact format
- [x] Dependencies
- [ ] Documentation only
- [ ] CI or developer tooling

### Commands and Results

- `python -m pytest tools/tests/test_architecture.py core/builder/tests/test_build.py families/qwen3_8/tests --ignore=families/qwen3_8/tests/test_e2e.py -q -rs`: **117 passed**, including 11 existing family tests.
- `ctest --test-dir "$BUILD" -R 'test_qwen3_8_recurrent_(output_initializers|pipeline)$' --output-on-failure`: **2 passed**, including the GPU pipeline, no skips.
- `python -m tools.model_ci validate`: inventory valid.
- Actual Model Connect paired ONNX build and public CLI inference passed. The publication runtime was rebuilt natively and repeated both quality checks against the same qualified engine bundle.
- Independent source-verified saved CPU FP32 oracle: exact tokens, **NED 0.0 <= 0.15**.
- Original Edge 128-token fixture, temperature1/topK50/topP1, chat enabled/thinking disabled: **ROUGE-1 0.4246 / ROUGE-L 0.2458 >= 0.25 / 0.20** again on the publication runtime.

- `npm --prefix website run test:model-support`: **7 passed**; `npm --prefix website run build`: **passed**, including34SVGchecks.

- `python -m tools.community_ci source-quality --base 730286693249502319888859c4fdb5b42d2d2104`: **passed**, including195checks with pinned Ruff0.16.4 and clang-format22.1.8. The formatting-only follow-up rebuilt the same byte-identical qualified runtime; both native tests passed again.

### Hardware, Environment, and Revisions

Native Linux x86_64 SM120, CUDA13.3, TensorRT11.1.0.106, FP16 execution with source mixed NVFP4/FP8 metadata, TP1/batch1/inputKV1024. Official GitHub Edge-LLM0.10.1 revision `e8b29522938901f6df19ebeedd4b69bc8edbcd97`; no internal checkout or cross-compilation.

Target `RadixArk/Qwen3.8-27B-NVFP4`, revision `319f741cce68d7914884900c138a1fbb70a42f30`; draft `RadixArk/Qwen3.8-27B-DSpark`, revision `b9a5dbdf03bc999c6c73c426b19c2d9041cea393`.

Qualified engine bundle SHA256: `0040c37107d68349f270af64bf9c60fbb050844805a7681013b4ec2546cf69fd`. The publication branch is based on generic prerequisite `ee91e1c71da243b0aaf7983a61cc2498b549adf7`.

### Not Run / Remaining Gaps

Exact-head Community CPU and protected internal CI passed; see the status below. This exact pair uses explicit local recipes with existing owning E2E helpers; it is **not a registered pytest manifest case**, and this PR does not imply internal CI executes it.

The publication cleanup removed unqualified branches and reused the original qualified engines; it did not repeat ONNX export/engine building. The independent reference was reused after source-byte/reference-function verification, not regenerated. Other platforms, standalone NVFP4 Edge execution, multimodal inputs, larger capacities and statistical sampling equivalence are not qualified.

## Contributor Self-Review

- [x] I have completed a self-review of this change.

Self-reviewed mixed-weight and paired-execution admission, explicit fallback limits, request capacity checks, independent-reference decoding, and unchanged quality gates.

## Notes For Future Readers

Depends on **#1305**, included until the generic prerequisite is merged. Review the generic SDK/build-input contracts first, then the family dispatch, paired runtime and existing E2E oracle changes.

The first rollout inference crash was caused by same-version but ABI-incompatible JSON development headers. The exact pinned headers fixed the same engines; the prerequisite retains a header-content check rather than a version-only check.

An Edge preparation failure warns and attempts the owning native callback once. Native Qwen3.8 cannot implement DSpark and fails explicitly instead of substituting base-only decoding. Inference and publication errors do not silently fall back.

No merge or auto-merge is requested. Website changes deploy only after approved merge.

### Risk level

- [ ] Low
- [ ] Medium
- [x] High

Complete-network paired offload adds native ABI and speculative-runtime dependencies. Exact platform/contract admission and repeated independent quality checks bound this profile, but automated pair registration and broader compatibility remain separate work.

Publication runtime SHA256: `b3d3b4b3b411af7f257736fde4d213cfc48c068bd47e879520d961be8a27c0d5`.

### Final protected CI status

Exact head `79c141b96e458ff3e2528ba73bde80f3a02f65e5`: Community CPU and `TRTMC Internal CI / Automated premerge gate` passed. This does not establish automated coverage for the locally qualified DSpark recipe, which is not registered in the owning E2E manifest. No merge or auto-merge requested.

Artifact lifecycle update: the successful local qualification bundles have now been retired under approved cleanup after verifying their recorded hashes. Compact outputs, quality results, source revisions and hashes remain. Fresh inference replay requires rebuilding the exact profiles; this does not change the executed qualification or exact-head CI results above.

### CODE REVIEW

File: families/qwen3_8/edge_llm/dispatch.py [hunk 1]
```diff
@@ -0,0 +1,100 @@
...
+            failure = error
+            with log_path.open("a", encoding="utf-8") as log:
+                traceback.print_exception(error, file=log)
+            _LOG.warning("qwen3_8 Edge build failed: %s. Diagnostics: %s. "
+                         "Retrying native once with the unchanged request.", error, log_path, exc_info=True)
+        else:
+            # Edge preparation did not touch writer; publication cannot fallback.
+            if adapter is not None:
+                edge_llm.publish(request, writer, files, marker)
+                return
```
[the remark this answers is not in the document]
Comment (JCalafato) [reply families/qwen3_8/edge_llm/dispatch.py:94]: Verified review follow-up (2026-09-21); current head ea39f8d1e4922670e64ae8b292999be9d8dcc0f8.

Fixed: remove the diagnostic only after successful publish. A local control-flow probe exercised success, preparation failure and publication failure: success removes the log, failures retain it, and publication errors do not trigger native fallback. Existing Qwen3.8 suite: 14 passed, 2 explicitly gated model E2Es skipped.

These are scoped regression checks, not a fresh full-model GPU qualification. Current-head CI is tracked separately.

File: families/qwen3_8/EDGE_LLM.md [hunk 2]
```diff
@@ -0,0 +1,60 @@
...
+Edge only for an explicit mixed-NVFP4 target plus DSpark companion.
+
+## Build and inference
+
+Provision the optional native SDK with `TRTMC_EDGELLM_ALL_KERNELS=ON` and
+`TRTMC_EDGELLM_ONNX=ON` using the
+[pinned package instructions](../../cmake/edgellm/README.md). The source is
+GitHub Edge-LLM0.10.1 at `e8b29522938901f6df19ebeedd4b69bc8edbcd97`.
+Configure `CMAKE_PREFIX_PATH` for the installed package and compile the runtime
+with `TRTMC_ENABLE_EDGELLM=ON`. Cross compilation is unsupported.
```
[the remark this answers is not in the document]
Comment (JCalafato) [reply families/qwen3_8/EDGE_LLM.md]: Verified review follow-up (2026-09-21); current head ea39f8d1e4922670e64ae8b292999be9d8dcc0f8.

Fixed the missing spaces throughout the qualification record, including dependency versions, capacity, sampling values, metric values and test counts. Numeric results and quality gates are unchanged.

These are scoped regression checks, not a fresh full-model GPU qualification. Current-head CI is tracked separately.

File: cmake/edge_llm/EdgeLLM.cmake [hunk 3]
```diff
@@ -0,0 +1,123 @@
...
+set(_edge_version "0.10.1")
+set(_edge_revision "e8b29522938901f6df19ebeedd4b69bc8edbcd97")
+set(_edge_root "${CMAKE_BINARY_DIR}/_deps/edgellm")
+set(_edge_prefix "${_edge_root}/install")
+set(TRTMC_EDGELLM_CUDA_ARCHITECTURE "${CMAKE_CUDA_ARCHITECTURES}" CACHE STRING "One local GPU architecture for Edge-LLM")
+if(NOT TRTMC_EDGELLM_CUDA_ARCHITECTURE MATCHES "^[0-9]+$")
+  message(FATAL_ERROR "Set TRTMC_EDGELLM_CUDA_ARCHITECTURE to one local GPU architecture, e.g. 80")
+endif()
+find_package(EdgeLLM ${_edge_version} EXACT CONFIG QUIET)
+if(EdgeLLM_FOUND AND NOT EdgeLLM_PREFIX STREQUAL _edge_prefix)
```
[the remark this answers is not in the document]
Comment (JCalafato) [reply cmake/edge_llm/EdgeLLM.cmake]: Fixed in prerequisite #1305 and included here. The initial reuse lookup clears a cached local EdgeLLM_DIR and excludes this build tree's package directory before importing any config; external packages remain discoverable. Fresh generated discovery is explicit after regeneration. Poison-package probes passed for cache, environment and prefix-path inputs, plus external reuse.

Verified on published head 418fd9adb0ab5d869514f2a731b1ee855057c34b. No full-model requalification is claimed.

File: core/builder/tensorrt_model_connect/build_cli.py [hunk 4]
```diff
@@ -66,16 +73,34 @@ def _parser(prepare_family: object | None = None) -> argparse.ArgumentParser:
...
     ):
         base_parser.error("MODEL must immediately follow prepare-structure")
-    preliminary, _ = base_parser.parse_known_args(arguments)
-    model_dir = _resolve_model(preliminary.model, preliminary.revision)
+    preliminary_arguments = (
+        [arg for arg in arguments if arg not in {"-h", "--help"}] if family_help else arguments
+    )
+    preliminary, unknown = base_parser.parse_known_args(preliminary_arguments)
+    if unknown and arguments[0] == "build" and arguments[1].startswith("-"):
+        base_parser.error("MODEL must immediately follow build when family options are used")
```
[the remark this answers is not in the document]
Comment (JCalafato) [reply core/builder/tensorrt_model_connect/build_cli.py]: Fixed in prerequisite #1305. The preliminary pass preserves unknown-token ordering without treating an unknown option's value as MODEL. Recognized core flags may precede MODEL; family options must follow it. Existing tests exercise --family/--verbose before MODEL and family-owned options afterward, while proving invalid pre-model options cannot download a checkpoint.

Verified on published head 418fd9adb0ab5d869514f2a731b1ee855057c34b. No full-model requalification is claimed.

File: families/qwen3_8/edge_llm/dispatch.py [hunk 5]
```diff
@@ -0,0 +1,148 @@
...
+    """Build the retained mixed-NVFP4 Qwen3.8 / DSpark block7 pair."""
+    execution.validate_local()
+
+    if execution.variant != "dspark" or tuple(x.role for x in execution.checkpoints) != ("draft",):
+        raise ValueError("Qwen3.8 paired execution requires variant=dspark and one draft checkpoint")
+    draft_dir = execution.checkpoints[0].model_dir
+    raw = json.loads((request.model_dir / "config.json").read_text())
+    draft = json.loads((draft_dir / "config.json").read_text())
+    if not candidate(request, raw) or edge_llm.checkpoint_quantization(request.model_dir, raw) != "nvfp4":
+        raise ValueError("The retained Qwen3.8 DSpark pair requires a matching mixed-NVFP4 base")
```
[the remark this answers is not in the document]
Comment (JCalafato) [reply families/qwen3_8/edge_llm/dispatch.py]: Fixed in Qwen3.8-owned dispatch. Precision and other request controls are validated separately before checkpoint compatibility checks. Omitting the paired profile's FP16 setting now explicitly requests --precision fp16 instead of blaming the checkpoint. The ordinary family default remains unchanged. Existing regressions cover unsupported controls and a distinct mixed-NVFP4 checkpoint error.

Verified on published head 418fd9adb0ab5d869514f2a731b1ee855057c34b. No full-model requalification is claimed.

File: families/qwen3_8/edge_llm/dispatch.py [hunk 6]
```diff
@@ -0,0 +1,148 @@
...
+            or any(type(i) is not int or not 0 <= i < base["num_hidden_layers"] for i in layers)
+            or len(set(layers)) != len(layers)):
+        raise ValueError("Invalid Qwen3.8 DSpark target layer IDs")
+    mask = config.get("mask_token_id", draft.get("mask_token_id"))
+    if type(mask) is not int or not 0 <= mask < base["vocab_size"]:
+        raise ValueError("Invalid Qwen3.8 DSpark mask token")
+    limit = request.max_sequence_length or min(base["max_position_embeddings"], 256)
+    capacity = draft.get("max_position_embeddings")
+    if type(capacity) is not int or not 8 < limit <= capacity:
+        raise ValueError("Requested context exceeds DSpark draft capacity or block minimum")
```
[the remark this answers is not in the document]
Comment (JCalafato) [reply families/qwen3_8/edge_llm/dispatch.py]: Fixed in Qwen3.8-owned build_paired: the unchanged 9–1024 profile bound is enforced before dispatch/preparation, with direct ValueError and no diagnostic file or native-fallback wrapper. Existing tests reject 8, 1025 and 2048, admit 9 and 1024, and verify the requested draft is preserved.

Verified on published head 418fd9adb0ab5d869514f2a731b1ee855057c34b. No full-model requalification is claimed.

File: families/qwen3_8/edge_llm/dispatch.py [hunk 7]
```diff
@@ -0,0 +1,166 @@
...
+    if draft.get("quantization_config") or any(
+        (draft_dir / name).exists()
+        for name in ("hf_quant_config.json", "quantize_config.json", "quant_config.json")
+    ):
+        raise ValueError("This Qwen3.8 DSpark profile requires unquantized draft weights")
+
+    def native_pair(original_request, original_writer):
+        # A failure must never replace the requested pair with base-only decoding.
+        raise NotImplementedError("Native Qwen3.8 does not implement the requested DSpark variant")
```
[the remark this answers is not in the document]
Comment (JCalafato) [reply families/qwen3_8/edge_llm/dispatch.py]: Fixed in Qwen3.8-owned dispatch. The native-pair error now names the qualified Linux x86_64, SM120 and FP16 Edge route while retaining the Native Qwen3.8 diagnostic. Existing tests cover SM90 and aarch64 non-matches and verify no staging/log remains. Qwen3.8 suite: 42 passed, two full-model E2Es gated/skipped.

Verified on published head 367cc5f0073dbca178bff792e52740e1acbf0291. No full-model requalification is claimed.

File: families/qwen3_8/edge_llm/README.md [hunk 8]
```diff
@@ -0,0 +1,101 @@
...
+A failed explicit pair is never replaced by a base-only bundle. Previously
+recorded full-model results above are historical, not fresh refactor-head E2Es.
+
+Request controls and the existing 9–1024 capacity range are checked before any
+Edge preparation. The native precision default is not changed: this paired
+profile explicitly requires FP16. Temporary staging uses the output filesystem.
+
+## Declared build command
+
+This family uses the existing cli.json protocol introduced in #1310. The family\nowns its declaration, typed inputs and Python handler. The handler adapts those\ninputs to the unchanged builder API, preserving native/Edge dispatch and bundle\npublication. The legacy flat build command remains available for its existing\nordinary options; new family options use `trtmc qwen3_8 build`.
```
[the remark this answers is not in the document]
Comment (JCalafato) [reply families/qwen3_8/edge_llm/README.md]: Addressed in c6f9c327790ef38da76d7f4103baf4210771f7a4. Replaced literal Markdown escape sequences with actual line breaks and apostrophes. Existing documentation builds pass; model values and qualification claims are unchanged.

File: website/docs/features/model-families.md [hunk 9]
```diff
@@ -66,6 +66,27 @@ long-context qualification remain outside this contract. The
 committed-token-per-forward receipt is an algorithmic diagnostic, not a
 wall-clock speedup claim.
 
+### Qwen3.8 paired ONNX execution
+
+Use `trtmc qwen3_8 build MODEL -o model.bundle` with the owning
+family\u0027s options. `trtmc qwen3_8 build --help` works offline without
```
[the remark this answers is not in the document]
Comment (JCalafato) [reply website/docs/features/model-families.md]: Addressed in c6f9c327790ef38da76d7f4103baf4210771f7a4. Replaced literal Markdown escape sequences with actual line breaks and apostrophes. Existing documentation builds pass; model values and qualification claims are unchanged.
